--------------------------------------------------------------------
-- 01_foundation.sql  –  Sprocket Phase 1 Foundation Infrastructure
--------------------------------------------------------------------

USE ROLE SPROCKET_DEPLOYER;

-- Schemas
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS MODELED;
CREATE SCHEMA IF NOT EXISTS SEARCH;
CREATE SCHEMA IF NOT EXISTS AGENT;
CREATE SCHEMA IF NOT EXISTS PIPELINE;
CREATE SCHEMA IF NOT EXISTS APP;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS SPROCKET_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND   = 60
    AUTO_RESUME    = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Stages
CREATE STAGE IF NOT EXISTS RAW.MANUALS_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE STAGE IF NOT EXISTS RAW.USER_UPLOADS_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE STAGE IF NOT EXISTS RAW.IMAGES_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- File Formats
CREATE FILE FORMAT IF NOT EXISTS RAW.JSON_FORMAT
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = TRUE;

CREATE FILE FORMAT IF NOT EXISTS RAW.CSV_FORMAT
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';
