--------------------------------------------------------------------
-- 01_foundation.sql  –  Sprocket Phase 1 Foundation Infrastructure
--------------------------------------------------------------------

USE ROLE SYSADMIN;

-- Database
CREATE DATABASE IF NOT EXISTS SPROCKET;

-- Schemas
CREATE SCHEMA IF NOT EXISTS SPROCKET.RAW;
CREATE SCHEMA IF NOT EXISTS SPROCKET.CURATED;
CREATE SCHEMA IF NOT EXISTS SPROCKET.SEARCH;
CREATE SCHEMA IF NOT EXISTS SPROCKET.APP;
CREATE SCHEMA IF NOT EXISTS SPROCKET.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS SPROCKET.PIPELINE;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS SPROCKET_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND   = 60
    AUTO_RESUME    = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Stages
CREATE STAGE IF NOT EXISTS SPROCKET.RAW.MANUALS_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE STAGE IF NOT EXISTS SPROCKET.RAW.USER_UPLOADS_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE STAGE IF NOT EXISTS SPROCKET.RAW.IMAGES_STAGE
    DIRECTORY = (ENABLE = TRUE)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- File Formats
CREATE FILE FORMAT IF NOT EXISTS SPROCKET.RAW.JSON_FORMAT
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = TRUE;

CREATE FILE FORMAT IF NOT EXISTS SPROCKET.RAW.CSV_FORMAT
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';
